---
title: "Unrivaled Team Rankings"
format: 
  html:
    fig-width: 10
    fig-height: 6
    toc: false
lightbox: true
---


```{r}
#| include: false
source('code/setup.R')
source('code/calcElo.R')
source('code/eloGraph.R')
```


::: {.panel-tabset}
## 2026

```{r}
#| echo: false
#| message: false
year <- 2026
sched <- getSchedule(year)
sched <- calcElo(sched)
sched2026 <- sched
```

```{r}
#| echo: false
#| message: false
#| classes: light-mode
makeUnrivaledEloGraph(year, sched, mode = 'light')
```

```{r}
#| echo: false
#| message: false
#| classes: dark-mode
makeUnrivaledEloGraph(year, sched, mode = 'dark')
```

## 2025

```{r}
#| echo: false
#| message: false
year <- 2025
sched <- readRDS('data/sched2025.rds')
```

```{r}
#| echo: false
#| message: false
#| classes: light-mode
makeUnrivaledEloGraph(year, sched, mode = 'light')
```

```{r}
#| echo: false
#| message: false
#| classes: dark-mode
makeUnrivaledEloGraph(year, sched, mode = 'dark')
```

:::


### About these plots

Elo ratings are a way of estimating a team's "true" skill level, invented by Arpad Elo to rank chess players ([Wikipedia](https://en.wikipedia.org/wiki/Elo_rating_system)). The rating system used here is a simplified version of the WNBA ratings system implemented by fivethirtyeight.com. Ratings reset to 1500 at the beginning of the season, since the rosters were redrafted.


# Recent Games


```{r}
#| echo: false
#| message: false
# get recent games
recent <- sched2026[which(!is.na(sched2026$score2)), ]
if(nrow(recent) > 6){
    recent <- recent[(nrow(recent)-5):nrow(recent), ]
}
plotGame <- function(game){
    par(mar=c(.1,.1,.1,.1))
    plot(0:1,0:1,col='transparent', axes=FALSE)
    rect(0,1/3,1,2/3, col=alpha(par("fg"),alpha=.1), border = NA)
    rect(0,0,1,2/3, col='transparent')
    # date, team names
    text(0,5/6, labels = format(game$date, "%a, %b %d"), pos = 4)
    text(0,.5, labels = game$team1, pos = 4, font = 2)
    text(0,1/6, labels = game$team2, pos = 4, font = 2)
    
    if(!is.na(game$score1)){ # game has already happened
        # Score
        text(1,5/6, labels = "Score", pos = 2)
        text(1,.5, labels = game$score1, pos = 2)
        text(1,1/6, labels = game$score2, pos = 2)
        # pre-game winProbs / correct pick
        probCol <- 2
        if(game$team2_winProb > .5 & game$score2 > game$score1){
            probCol <- 3
        }
        if(game$team2_winProb < .5 & game$score2 < game$score1){
            probCol <- 3
        }
        text(.9,.5, labels = paste0(format(100*(1-game$team2_winProb), digits = 3, nsmall = 1),'%'), pos = 2, cex = .67, col = probCol)
            text(.9,1/6, labels = paste0(format(100*(game$team2_winProb), digits = 3, nsmall = 1),'%'), pos = 2, cex = .67, col = probCol)
    }else{ # game is upcoming
        # WinProb
        text(1,5/6, labels = "WinProb", pos = 2)
        if(!is.na(game$team2_winProb)){
            text(1,.5, labels = paste0(format(100*(1-game$team2_winProb), digits = 3, nsmall = 1),'%'), pos = 2)
            text(1,1/6, labels = paste0(format(100*(game$team2_winProb), digits = 3, nsmall = 1),'%'), pos = 2)
        }
    }
}
```

```{r}
#| echo: false
#| message: false
#| fig-height: 1.5
#| fig-width: 8
#| classes: light-mode
layout(matrix(1:2, nrow=1))

par(mar = c(5,5,4,0)+.1, cex.lab = 1.25, cex.main = 2, bg = '#fffaf6')
for(i in rev(seq_len(nrow(recent)))){
    game <- recent[i,]
    plotGame(game)
}

```

```{r}
#| echo: false
#| message: false
#| fig-height: 1.5
#| fig-width: 8
#| classes: dark-mode
layout(matrix(1:2, nrow=1))

par(mar = c(5,5,4,0)+.1, cex.lab = 1.25, cex.main = 2, bg = '#fffaf6')
par(fg = 'white', bg = '#272935', col.axis = 'white', col.lab = 'white', col.main = 'white', col.sub = 'white')

for(i in rev(seq_len(nrow(recent)))){
    game <- recent[i,]
    plotGame(game)
}

```


